PLATF-143-alter-validation-for-externally-hosted-apps
Metrological/metrological-cli pull request #3
Opened 2022-11-04 16:02 UTC by robbertvancaem

2022-11-04 18:53 UTC, robbertvancaem commented on src/actions/upload/index.js
> +  if (!isExternalApp) {
This is incorrect, the `static` folder should also be copied for externally hosted apps (because at least the icons should be in there)

2022-11-07 08:02 UTC, mauro1855 requested changes
Some properties in the metadata JSON schema validator that are required should not be. Please address it.

2022-11-07 08:39 UTC, robbertvancaem commented on src/actions/upload/validate-metadata.js
> +    icons: {
Do you know if `icons` only contains operator specific icons? And is `icon` used by default if `icons` are not provided? Because then I would indeed agree that the `icons` object should be optional

2022-11-07 08:50 UTC, robbertvancaem commented on src/actions/upload/validate-metadata.js
> +    version: { type: 'string', required: true, pattern: SEMVER_PATTERN },
I guess it depends on what the platform supports. I assumed any `-alpha` flags in version numbers caused issues in the past, but it makes sense to reevaluate this to indeed let developers decide for themselves if it doesn't cause technical issues (but then we should use alpha/beta releases ourselves hehe)

2022-11-07 08:52 UTC, robbertvancaem commented on src/actions/upload/index.js
> +  if (!isExternalApp) {
Currently (before this change) it is required all of the files, so a `src` and `static` folder as well as `appBundle.js`. In this PR I changed this to only copy the `metadata.json`, but this is incorrect. Any static files should be copied as well.

2022-11-07 08:53 UTC, robbertvancaem commented on package.json
> +  "engines": {
It's an indication of what version of Node is assumed to be used for this package to work. It's not in 'strict mode', so if it's installed on previous versions of Node it will only show a warning. 

https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines

2022-11-07 15:14 UTC, giorgiomazzei79 commented on jest.config.js
> +  // All imported modules in your tests should be mocked automatically
Yes, I would remove the comments.
This is the standard file created by Jest with the built in comments.
We can always go to the docs and check how to add additional commands.

2022-11-07 15:17 UTC, giorgiomazzei79 commented on bin/index.js
> +require('dotenv').config();
The listing of this lines with basically no changes makes the PR less readable.
I usually remove these specific changes.

2022-11-07 15:19 UTC, giorgiomazzei79 commented on package.json
> +  "version": "1.1.0",
`package-lock.json` is still at version 1.0.0.

please run `npm i` again to update it.

2022-11-07 15:26 UTC, giorgiomazzei79 commented on bin/index.js
> +      uploadAction();
Isn't it enough to have a catch on uploadAction()?
Doesn't it already return a promise with a possible error already caught?

2022-11-10 18:16 UTC, robbertvancaem commented on bin/index.js
> +      uploadAction();
It returns an async function, with function calls that can fail elegantly or just throw an error. With these lines I want to make sure every error gets caught regardless.

2022-11-10 18:19 UTC, robbertvancaem commented on bin/index.js
> +require('dotenv').config();
These changes are in here because I introduced eslint as a linter and formatter in this PR. I want all files in the repo to play nice with the eslint configuration, so that's why I changed them. In future PR's, these changes will not be in there because their base reference is the same: the eslint configuration :-)

2022-11-10 18:19 UTC, robbertvancaem commented on jest.config.js
> +  // All imported modules in your tests should be mocked automatically
Agreed, will change this

2022-11-10 18:46 UTC, robbertvancaem commented on src/actions/upload/validate-metadata.js
> +    version: { type: 'string', required: true, pattern: SEMVER_PATTERN },
Decided to not enforce any pattern for now, since this would have to be decided by the entire team (and incorporated on multiple levels before enforcing it from the CLI)

2022-11-10 18:50 UTC, robbertvancaem commented on package.json
> +  "version": "1.1.0",
Updated!

2022-11-10 18:51 UTC, robbertvancaem commented on src/actions/upload/validate-metadata.js
> +    icons: {
Changed it to not require `icons`

2022-11-10 18:51 UTC, robbertvancaem commented on src/actions/upload/index.js
> +  if (!isExternalApp) {
Corrected it so that `./static` is always copied over

2022-11-10 18:52 UTC, robbertvancaem commented on src/actions/upload/validate-metadata.js
> +        '1920x1080': { type: 'string', required: true, pattern: ICON_PATTERN },
Changed it so that the properties for `artwork` aren't required (until it's properly documented and enforced from the backend as well)

2022-11-14 11:25 UTC, michielvandergeest commented on readme.md
> +### Method 2: Installing as a devDependency
You might want to rethink suggesting this as a method of installing the metro-cli.

It's definitely possible to make the metro CLI a dependency of the App. But then you run the risk of having outdated dependencies on a per App basis (and having to do app updates whenever new crucial metro-cli functionality is released).

Before the Lightning-CLI existed the upload functionality was an App dependency and the Lightning-CLI solved that problem by being a global install.

2022-11-22 14:26 UTC, robbertvancaem commented on readme.md
> +### Method 2: Installing as a devDependency
@michielvandergeest Fair point. It's ofcourse merely a suggestion, and not the preferred method. Since it's a `devDependency` it will not influence the bundle size, nor does it influence the behaviour of the app itself.

You are right in stating that the metro-cli needs to be updated per app, but this is fine. Perhaps it should be pointed out in the documentation as well if we get feedback that it leads to issues.

2022-11-23 15:53 UTC, michielvandergeest commented on readme.md
> +### Method 2: Installing as a devDependency
@robbertvancaem Sure! It won't affect the App indeed, but it can complicate your process further down the road. So just sharing that experience here.

Totally up to you if you want to even suggest it as a method or not at all :)

2022-11-23 16:02 UTC, giorgiomazzei79 commented on bin/index.js
> +      uploadAction();
Found this interesting conversation:
https://stackoverflow.com/questions/69362121/when-should-i-use-try-catch-instead-of-then-catch

2022-11-23 16:21 UTC, giorgiomazzei79 commented
Apart of the comments made there's nothing that in my eyes (code review) blocks this PR from being merged, but I feel someone else with more insight in the matter should approve.

I can approve if nobody else is available.

2022-12-19 09:59 UTC, Thomvl approved these changes
LGTM

2022-12-20 09:26 UTC, merged